service_name: '6f0f309e-5451-4a62-8a3a-7bca5404e6f8'

http:
  url: http://0.0.0.0:9000
  cors:
    access_control_allow_headers:
      - Content-Type
      - Cache-Control
      - Authorization
      - X-Total-Count
    access_control_allow_origin:
      - https://go2.uiscom.ru

uc_flow_node:
  register_on_start: false
  execute_view_queue_size: 500
  execute_view_workers: 5
  private_url: https://ce43-5-189-94-93.ngrok-free.app
  public_url: https://ce43-5-189-94-93.ngrok-free.app
  uc_flow:
    domain: https://uc-flow-v2-pp-api.comagic.ru
    jwt_secret: 9109a79d-74f9-45bd-b369-5e7a885421e5